### ISSUE TITLE
Updates to Mongo

### ISSUE THREAD

**Issue by joshuaylevy** [joshuaylevy/ioCapture#19]
## Features to add
- [ ] Storing `nber_program` as an array of strings rather than as a string of programs
- [ ] Generate hashed IDs for institutions, firms, journals
- [ ] Adding details on timestamped CV (see below)

## Bug fixes
- [x] Handling `scopus_author_id` as an integer rather than as a string

## Documentation 
- [x] Comment your CVtoJSON.py file
- [x] Write a README.txt for how to run your file so that a technically capable new team member could replicate your work

**Comment by joshuaylevy** [comment]
## Adding details on time-stamped CVs

In the existing JSON example that is the format/template for a Mongo document, in multiple locations we have a `_edited_source` field that describes where certain information was collected from. For example:
``` json
{
"industry" : {
        "consulting" : [
            {
                "firm_name" : "Uber Inc.",
                "firm_id" : "#firm99",
                "firm_sector" : "transportation",
                "consulting_start" : 2018,
                "consulting_end" : 9999,
                "consulting_title" : "academic affiliate",
                "_edited_source" : {
                    "created" : "datetimeobject",
                    "created_source" : "Cv/document/path",
                    "last_updated" : "datetimeobject",
                    "updated_path" : "CV/document/path2",
                    "disclosure_place" : "CV",
                    "disclosure_quality" : "bad."
                }
            }
        ],
}
```

We will eventually get to filling these out by parsing CVs etc. However, I think we should also create a top-level field for whether or not a time-stamped CV is on file.  So, the top of the new Mongo document might look like something like as follows:
``` json
{
    "author_first_name" : "Joshua",
    "author_middle" : "Yuki",
    "author_last_name" : "Levy",
    "object_id" : "#123456789",
    "scopus_author_id" : "4567890",
    "personalwebsite" : "https://url",
    "departmentwebsite" : "https://url",
    "disclosurewebsite" : "https://url",
    "nberwebsite" : "https://url",
    "nber_info" : {
        "nber_status": "faculty_research_fellow",
        "nber_programs" : [
            "political economy", 
            "development",
            "corporate finance"
        ]
    },
    "sex" : 0,
    "latest_cv" : {
         "latest_cv_path" : "[latest_cv_path goes here ]",
         "latest_cv_timestamp" : "[latest_cv_timestamp timestamp goes here]"
    }
    ...

}

```

It's up to you what type the `latest_cv_timestamp` field should be (string or dateTime object depending on what you think works best between Python/Mongo) but I think that the `latset_cv_path` field should just be a string.

I have uploaded the existing time-stamped CVs to the DropBox folder at the following location: `99_01_Database_Construction/cvs/stamped_cvs`. I have created some other folders that I think are relatively self-explanatory (let me know what you think). The reason for the weird "99_" prefix is that Aditya and I are in the process of updating the structure of the DropBox folders and I don't want to break anything yet. the "99_" prefixes are the destination ones so you should write code based on the internal structure of these folders. Because we don't want to push the data files to GitHub we store them in the DropBox which should have a (not right now but eventually) identical folder structure as the repo so that we can copy-paste data files to our local repos as necessary (**make sure to keep your .gitignore file up to date!**). I'm not quite sure how to handle program-level folders because there are eventually going to be a lot of scholars who are not affiliated with the NBER. Let's think about this and regroup.

**Comment by jkl-cmu** [comment]
Got it. I'll try to work on seeing how to add these features this weekend and report to you by Monday. I'll just try to get as much done as I can.

I just fixed the SCOPUS IDs being extracted as str instead of ints and added some basic documentation (comments and a readme).
I may have messed up because the pull request for that is separate from this.

**Comment by joshuaylevy** [comment]
In re the last bit, you're good because you didn't reference this task/"issue's" number. This will stay here until you invoke the number  in a PR or a commit with one of the [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Maybe give this a try when you submit your next PR!
